import '../styles/globals.css'

import React from 'react'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'upload-ai',
  description: 'Generated by create next app'
}

import { fontInter } from '~/libs/font'

import { Header } from '~/components/Header'
import { Providers } from '~/components/Providers'

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-br" className={fontInter.variable} suppressHydrationWarning>
      <body>
        <Providers>
          <Header />

          <>{children}</>
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
