import '../styles/globals.css'

import React from 'react'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'upload-ai',
  description: 'Generated by create next app'
}

import { fontInter } from '~/libs/font'

interface RootLayoutProps {
  children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="pt-br" className={fontInter.variable}>
      <body>{children}</body>
    </html>
  )
}

export default RootLayout
